### ISSUE TITLE
Not using BPs during AC

### ISSUE THREAD

**Issue by Heretic6667** [ekrividus/AFAC#1]
Tested this out today, unfortunately didn't seem to work as outlined.  Default delay settings were used.

It worked fine until 18:51:18 in the log, but then it seemed to think it was all done with astral conduit.  You can see that astral conduit doesn't fire off until 18:51:19, meanwhile a second prior it prints to the log that we're done.  

30 seconds later AC wears off without any additional volt strikes while AC was active.  Seems some sort of delay or check of some kind is firing off prematurely?  

I tried this on 2 mules, same results on both.

Appreciate any possible fix :)

P.S. either the ingame "//afac mp #" command has no effect, or the "//afac show" command just shows 300 mp no matter what you changed the mp convert value to.

**Comment by ekrividus** [comment]
Yeah that's not great.
This addon was still in a fledgling state when I stopped playing for snowboard season, though I thought it was properly completing the cycle last I played.
When I return over the next few weeks I'll be digging into a handful of issues, this will certainly make the list.

P.S. that one I'll look at right now as it's probably super simple and silly typo on my part

**Comment by ekrividus** [comment]
With the exception of lag spikes causing wonkiness this will now properly AFAC.

**Comment by ekrividus** [comment]
With the exception of lag related wonkiness AFAC will run as expected.
Do make sure gearswap locks your AFAC set to avoid being in the wrong gear :)
